### ISSUE TITLE
Implement special case ridge regression for pi (e.g., only one covariate)

### ISSUE THREAD

**Issue by drisso** [drisso/archive-zinbwave#15]

**Comment by drisso** [comment]
This refers to zinbInitialize()

**Comment by jpvert** [comment]
Done.
The new solveRidgeRegression() solves least-squares and logistic regression problems, with (weighted) L2 penalty and offsets, and works for any number of covariates. This simplifies a lot the code. It directly optimizes the objective function with the optim() function; I did not profile how fast it is compared to glmnet() or lm.ridge(), but it seems ok on small problems (and anyway we only use it for initialization so I don't expect it to influence a lot the total speed of zinbFit).
