### ISSUE TITLE
glmnet() does not work when only 1 or 0 in one category

### ISSUE THREAD

**Issue by drisso** [drisso/archive-zinbwave#16]
That means that we cannot use it when there are genes and/or samples with only 1 or no zeros.

**Comment by jpvert** [comment]
Fixed. 
We don't use glmnet anymore, but solveRidgeRegression() which works even when there are only 1's and 0's. We have to be careful that in that case, the maximum likelihood estimator diverges to Inf; so by defaults there is a nonzero regularization epsilon for alpha_pi, beta_pi and gamma_pi. We may run into problems if the users explicitly sets the regularization to 0 and has samples and/or genes with only 1 or 0's, but hey he should think twice then.
