### ISSUE TITLE
consistency in dimensions between Y and getMu(), getPi()

### ISSUE THREAD

**Issue by fperraudeau** [drisso/archive-zinbwave#26]
It is a really minor thing, but it can annoy people.
Y has genes in rows, samples in columns.
getMu() and getPi() have samples in rows and genes in columns.
For example:

bio <- gl(2, 3)
Y <- matrix(rpois(60, lambda=5), nrow=10, ncol=6)
m <- zinbFit(Y, X=model.matrix(~bio))
dim(Y)
dim(getMu(m))
dim(getPi(m))

**Comment by drisso** [comment]
I think you are right. All the matrices returned to the user should have the same dimensions.
