### ISSUE TITLE
the world of the epsilons

### ISSUE THREAD

**Issue by fperraudeau** [drisso/archive-zinbwave#27]
I think now I understand which epsilon is which, but I was confused when I looked at the package for the first time. Probably because I did not look at the model carefully. 

What confused me is that **stop.epsilon.optimize** (stopping criterion in the optimization step, when the relative gain in likelihood is below epsilon (default 0.0001)) has nothing to do with **epsilon** (unique regularization parameter which stands for epsilon_W, epsilon_alpha, ....). Then, default for epsilon is 0.001. And I did zinb@epsilon_W and did not get 0.001. Then, I read the documentation and found that epsilon_W = epsilon/n.

Maybe, a way to clarify would be to write the formulas in the R documentation of zinb
$\epsilon_\beta = \frac{\epsilon}{J}$
$\epsilon_\gamma = \frac{\epsilon}{n}$
$\epsilon_W = \frac{\epsilon}{n}$
$\epsilon_\alpha = \frac{\epsilon}{J}$
$\epsilon_\zeta = \epsilon$

**Comment by drisso** [comment]
Fixed in 52dfbd1e3b986aa11077695ea5a2282b70cc970c
