### ISSUE TITLE
Possible conflict between branches

### ISSUE THREAD

**Issue by jpvert** [drisso/archive-zinbwave#28]
I realize I did some push to the master branch in september that are not reflected in the current develop branch, which I think Davide (and Fanny?) are working on.

In particular, the "old" version of model2.Rmd (and .pdf), which is still in the "develop" branch, finishes by a "TODO: write gradient...". The "new" version, which is in the master branch, finishes with a new section entitled "Solving \texttt{solveZinbRegression}". I believe there are also a few typos throughout the text that I may have corrected in the "new" version. I am not fully sure whether other files may have changed too.

@drisso : could you resolve the possible conflict between master and develop branches?

**Comment by drisso** [comment]
Fixed by merging master into develop
