### ISSUE TITLE
Clustering after model fitting

### ISSUE THREAD

**Issue by nachocab** [drisso/archive-zinbwave#32]
Hi, great package! 
Do you have a recommended way of doing the clustering after getting the W matrix? 

Also, it would be great to get some kind of gene loading information for feature selection. Is this currently possible?

**Comment by drisso** [comment]
Thanks! 
We don't have any recommended way for the clustering specifically linked with the zinb-wave method, but we have a different package, [clusterExperiment](bioconductor.org/packages/clusterExperiment), that implements a few strategies that we think work nice in single-cell data. ClusterExperiment has an extensive vignette, but briefly, it implements resampling-based, sequential clustering, which seems to lead to stable results.

As for the gene "loading" information, these are computed separately for mean expression, $\mu$, and probability of zero, $\pi$, and you can access them as the $\alpha_\mu$ and $\alpha_\pi$ slots in the `zinbFit` object, or with

```{r}
m@alpha_mu
m@alpha_pi
```
Assuming that your zinbFit object is called `m`.

We should probably add a `get_alpha_mu` and `get_alpha_pi` methods.

**Comment by nachocab** [comment]
Awesome! Thanks a lot for your help!!
