### ISSUE TITLE
Add sticker to BiocStickers repo

### ISSUE THREAD

**Issue by jorainer** [drisso/archive-zinbwave#37]
@drisso , please add your sticker to the https://github.com/Bioconductor/BiocStickers/ repo once you submitted your package to bioc (eventually already now ;) ). Sticker is awesome!

**Comment by drisso** [comment]
Thanks! :)
Was planning to do that after submission to Bioc! (Which happened today... so will add it soon!)

Also, @fperraudeau is responsible for the awesomeness of the sticker! :)

**Comment by drisso** [comment]
Done!

https://github.com/Bioconductor/BiocStickers/pull/29
