### ISSUE TITLE
zinbwave() error: initial value in 'vmmin' is not finite

### ISSUE THREAD

**Issue by drisso** [drisso/archive-zinbwave#44]
```{r}
Error in optim(fn = zinb.loglik.regression, gr = zinb.loglik.regression.gradient,  :
  initial value in 'vmmin' is not finite
```

See #34

**Comment by JohnReid** [comment]
I might have spotted my mistake. I am using the floating point count estimates from Salmon rather than integer counts. I will try again with integer counts. It would be nice to have a clearer error message though. Thanks for your help.

**Comment by drisso** [comment]
I agree about the error message (see #36). Let me know if rounding fixes it and I will close this.

**Comment by JohnReid** [comment]
Rounding fixed this one. One quick question, if I pass a `SingleCellExperiment` object with several assays into `zinbwave`, how do I tell `zinbwave` which assay to use? Does it always use the first one?

**Comment by drisso** [comment]
Yes, right now it only uses the first assay. I should definitely add an option to use a different one.
Thanks for pointing this out!
