### ISSUE TITLE
coding style!

### ISSUE THREAD

**Issue by drisso** [drisso/archive-zinbwave#7]
Since we're in at least three people to write and submit code to the repo, I thought that it would be useful to have some coding style guidelines. Please feel free to add more.

Right now we have a mix of coding styles. Both http://bioconductor.org/developers/how-to/coding-style/ and http://r-pkgs.had.co.nz/style.html recommend "<-" over "=", so I'll change that everywhere.

Please, use "<-" for assignment from now on.

As for object names, we currently have a mix of `this_name` and `thisName`. I'm fine with both, but I slightly prefer the latter, since it's consistent with our clusterExperiment package (but scone uses the former, damn! :)). It also seems that @jpvert has written many function in the camelCaps, so if you all agree, we can turn everything to camelCaps. But let me know if you prefer underscores and we can do that instead!

Other style points that we should try to respect when possible:
- Limit each line of code to 80 characters.
- Space after commas and around operators.
- Do not use "function.name" syntax.
- Use "." at the beginning of non-exported functions.

**Comment by jpvert** [comment]
Agree with all. camelCaps ok. Thanks for doing the cleaning (no need perhaps to clean functions_sim. R and functions_jp.R as the functions there will likely move to other files like functions_zinb.R and be corrected)

**Comment by drisso** [comment]
OK. Now everything should be in camelCaps. I'm leaving this open as a reference for the style.

**Comment by drisso** [comment]
I think we reached a point in development, where the style is clear from the code itself, hence closing this.
