### ISSUE TITLE
consider importing nSamples and nFeatures instead of using getN and getJ

### ISSUE THREAD

**Issue by drisso** [drisso/archive-zinbwave#8]
We have nSamples and nFeatures methods in clusterExperiment.

I'm hesitant just because N and J refer nicely to the model.

**Comment by jpvert** [comment]
I'd vote for nSamples and nFeatures (and probably also nFactors to replace getK), as they are more universal and easier to understand for someone who did not study the model notations

**Comment by drisso** [comment]
OK! I'll modify them tonight or tomorrow!

**Comment by drisso** [comment]
Closed with commit 17f2e1ee40dc11c39dc4cab869aaa97dacff27dc c8446f6974fcf1c9ab5983843913c837d91a3ca1 and d2c26fd1258571164ae8878353c83898fc6c75f2
